---
sidebar: sidebar 
permalink: concept-ransomware-protection.html 
keywords: artificial intelligence, personal data, personal information, sensitive, personal sensitive data, data sense, ransomware, ransomware protection, cyberstorage, cyber attack, cybersecurity 
summary: 랜섬웨어 공격은 비즈니스 시간, 리소스 및 평판에 악영향을 줄 수 있습니다. 랜섬웨어 보호 서비스를 통해 사이버 보안에 대한 관련 정보를 보고 사이버 공격에 대한 조직의 복원력을 평가할 수 있습니다. 또한 알림 목록과 데이터 보안 개선을 위한 해결 방법도 제공합니다. 
---
= 랜섬웨어 차단 에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
랜섬웨어 공격은 비즈니스 시간, 리소스 및 평판에 악영향을 줄 수 있습니다. 랜섬웨어 보호 서비스를 통해 사이버 보안에 대한 관련 정보를 보고 사이버 공격에 대한 조직의 복원력을 평가할 수 있습니다. 또한 알림 목록과 데이터 보안 개선을 위한 해결 방법도 제공합니다.

https://cloud.netapp.com/cyberstorage["랜섬웨어 차단 의 사용 사례에 대해 알아보십시오"^].


TIP: 랜섬웨어 보호 서비스는 현재 베타 버전입니다.



== 피처

랜섬웨어 차단 기능은 단일 가시성 및 제어 지점을 제공하여 다양한 작업 환경과 인프라 계층에서 데이터 보안을 관리 및 세분화하여 위협이 발생했을 때 보다 효과적으로 대응할 수 있도록 지원합니다. 현재 사이버 스토리지 보호 작업에 도움이 되는 여러 기능을 제공하고 있습니다. 향후 추가 기능이 추가될 예정입니다. 현재 기능은 다음과 같은 경우에 식별합니다.

* 작업 환경의 볼륨은 정기적인 Snapshot 복사본을 만들어 보호되지 않습니다.
* 를 사용하여 클라우드에 백업을 생성하면 작업 환경의 볼륨이 보호되지 않습니다 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-backup-to-cloud.html["클라우드 백업"^].
* 작업 환경 및 데이터 소스의 데이터는 를 사용하여 스캔되지 않습니다 https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["클라우드 데이터 감지"^] 규정 준수 및 개인 정보 보호에 대한 우려 사항을 파악하고 최적화 기회를 찾습니다.
+
이 기능은 랜섬웨어 보호 관점에서도 중요합니다. 중요한(비즈니스에 중요한) 데이터의 위치를 더 잘 이해하여 보호에 집중할 수 있기 때문입니다.

* 랜섬웨어 공격으로 인해 복구해야 할 경우 가장 중요한 범주의 데이터가 백업되지 않습니다.
* 작업 환경 또는 데이터 소스에서 암호화된 파일의 비율이 비정상적으로 증가했습니다.
+
이는 네트워크에서 랜섬웨어 공격이 시작했다는 것을 나타내는 지표가 될 수 있습니다.

* 파일에서 중요한 데이터가 검색되고 작업 환경 또는 데이터 소스에서 액세스 권한 수준이 너무 높습니다.
* 사용자가 Active Directory 도메인 관리자 그룹에 추가되었습니다.
* 클러스터의 ONTAP 소프트웨어 버전은 오래되었으며 최상의 보호 및 보안 기능을 제공하도록 업데이트해야 합니다.
* ONTAP 시스템에서 NAS 파일 시스템 감사가 설정되지 않았습니다.
+
CIFS 감사를 설정하면 시스템 관리자가 폴더 권한 변경, 파일 읽기 또는 쓰기 실패, 파일 생성, 수정 또는 삭제 시기 등의 정보를 추적하는 감사 이벤트가 생성됩니다.

* 온박스 안티 랜섬웨어 기능은 ONTAP 시스템에서 지원되지 않습니다.
+
ONTAP의 랜섬웨어 방지 기능은 랜섬웨어 공격을 나타낼 수 있는 비정상적인 활동을 사전에 감지하여 경고합니다.



link:task-analyze-ransomware-data.html["랜섬웨어 보호 대시보드에서 이러한 잠재적인 문제를 확인하는 방법을 알아보십시오."]

Cloud Volumes ONTAP 시스템을 사용할 경우 작업 환경에서 직접 배포할 수 있는 몇 가지 추가적인 랜섬웨어 보호 기능이 있습니다. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-protecting-ransomware.html["랜섬웨어에 대한 보호를 강화하는 방법을 알아보십시오"^].



== 지원되는 작업 환경 및 데이터 소스

https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["클라우드 데이터 감지"^] 랜섬웨어 보호 서비스를 이용하려면 사전 요구사항이 있어야 합니다. Data Sense를 설치 및 활성화한 후 랜섬웨어 Protection을 사용하여 다음 유형의 작업 환경 및 데이터 소스에 대한 사이버 공격에 데이터가 얼마나 복원되는지 확인할 수 있습니다.

* 작업 환경: *

* Cloud Volumes ONTAP(AWS, Azure 또는 GCP에 구축)
* 온프레미스 ONTAP 클러스터
* Azure NetApp Files
* ONTAP용 Amazon FSx
* Amazon S3


* 데이터 소스: *

* 비 NetApp 파일 공유
* 오브젝트 스토리지(S3 프로토콜 사용)
* 데이터베이스(Amazon RDS, MongoDB, MySQL, Oracle, PostgreSQL, SAP HANA, SQL Server)
* OneDrive 계정
* SharePoint 계정
* Google Drive 계정


또한 랜섬웨어 차단 기능은 글로벌 Active Directory 구성이 있는 경우 모니터링하기도 합니다 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-add-active-directory-datasense.html["클라우드 데이터 센스에서 구성했습니다"^].



== 랜섬웨어 차단의 작동 방식

고수준에서 랜섬웨어 차단은 다음과 같이 작동합니다.

. 랜섬웨어 방지 기능은 스토리지 시스템, Cloud Data Sense, Cloud Backup 및 기타 Cloud Manager 리소스에서 정보를 수집하여 랜섬웨어 보호 대시보드를 채웁니다.
. 랜섬웨어 보호 대시보드를 사용하여 시스템의 보호 기능을 대략적으로 파악할 수 있습니다.
. 제공된 보고 툴을 사용하여 사이버 스토리지 보호 노력을 지원할 수 있습니다.




== 비용

Beta 기간 중에는 랜섬웨어 보호 서비스에 별도의 비용이 들지 않습니다.
